### ISSUE TITLE
text should be multilingual where available

### ISSUE THREAD

**Issue by ggladman** [opensmc/smcfluclinics#1]
The flu clinic application should provide an English/Spanish language selection, and the underlying data should provide Spanish text wherever available. Potential dual-language fields include "restrictions" and "notes".

**Comment by rareitmeyer** [comment]
I think this is fixed. Can you please test, and close if it works for you?

**Comment by ggladman** [comment]
Richard's code for replacing translated strings is in place in the master branch now. Thanks, Richard!
