### ISSUE TITLE
When scrolling the map to the south, it's possible to scroll the page instead

### ISSUE THREAD

**Issue by rareitmeyer** [opensmc/smcfluclinics#4]
If you flick upward at the bottom of the map, it's (barely) possible to move the whole page
upward. This scrolls the menubar up, and can leave it unaccessible until you mange to scroll the page back down.

While this issue is rare, it will be hard for a casual user to figure out what's happened and how to fix.

**Comment by rareitmeyer** [comment]
I think this is fixed in my last checkin. Can someone test, and close or update as appropriate?

**Comment by ggladman** [comment]
Looks good in latest version. Thanks, Richard!
