### ISSUE TITLE
Translator(s) should be able to work in a spreadsheet, rather than JSON

### ISSUE THREAD

**Issue by rareitmeyer** [opensmc/smcfluclinics#5]
Initial work on translations has them all in a .JSON file for benefit of the app.

But JSON is not very friendly for a non-technical person to edit, and (as a Code for America project) we should make it easy for someone with knowledge of Spanish or Chinese to edit the translations without knowing JSON syntax.

Suggest enabling use of spreadsheet by allowing conversions from JSON to CSV and back.

Workflow would be for translator to take CSV, edit it, and check it in. They, or a developer, would then turn the CSV into JSON as part of building the app.

**Comment by rareitmeyer** [comment]
Added python(3) tools to www/js to convert from JSON to CSV and back. If someone can test....

**Comment by matthewnorman** [comment]
I can validate that the scripts work. See the `move_scripts` branch for the test. Unsure if we want to merge that branch because it moves the scripts so that they are importable.
